repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff
        args:
          - --fix

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        stages: [manual]
        args:
          - --quiet-level=2
          - --ignore-words-list=hass,ba,fo
          - --exclude-file=custom_components/hacs/utils/default.repositories

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        stages: [manual]
      - id: requirements-txt-fixer
        stages: [manual]
      - id: check-ast
        stages: [manual]
      - id: mixed-line-ending
        stages: [manual]
        args:
          - --fix=lf
